### ISSUE TITLE
Export Layers encountered an unexpected error and has to close. Sorry about that!

### ISSUE THREAD

**Issue by XeroPhane** [khalim19/gimp-plugin-export-layers#33]
Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\32\lib\gimp\2.0\python\gimpplugin.py", line 58, in _run
    return apply(getattr(self, name), params)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers.py", line 127, in plug_in_export_layers
    self._run_export_layers_interactive(image)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\pygimplib\pggui.py", line 352, in func_wrapper
    func(self, *args, **kwargs)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers.py", line 163, in _run_export_layers_interactive
    gui_plugin.export_layers_gui(image, self.settings, self.session_source, self.persistent_source)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\gui_plugin.py", line 612, in export_layers_gui
    _ExportLayersGui(image, settings, session_source, persistent_source)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\gui_plugin.py", line 229, in __init__
    _setup_image_ids_and_directories_and_output_directory(self.settings, self.image)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\gui_plugin.py", line 185, in _setup_image_ids_and_directories_and_output_directory
    current_image, settings['gui_session']['image_ids_and_directories'].value[current_image.ID])
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\pygimplib\pgsetting.py", line 1082, in update_current_directory
    self.set_value(directory_for_current_image)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\pygimplib\pgsetting.py", line 1069, in set_value
    super(DirectorySetting, self).set_value(value)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\pygimplib\pgsetting.py", line 323, in set_value
    self._assign_and_validate_value(value)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\pygimplib\pgsetting.py", line 460, in _assign_and_validate_value
    self._validate(value)
  File "C:\Users\username\.gimp-2.8\plug-ins\export_layers\pygimplib\pgsetting.py", line 1001, in _validate
    self._value_to_str(value) + "\n".join([message for message in new_status_messages])
SettingValueError: "C:\Users\username\Desktop\Client Experiences\ Site and Structural Design - Positioning": Path components in the directory path cannot start or end with spaces.

**Comment by khalim19** [comment]
Thank you for your report, [I've fixed it](https://github.com/khalim19/gimp-plugin-export-layers/archive/477d23d032cd5372d95d16729b1acf28757c9a95.zip).
