### ISSUE TITLE
Export layers Crashed

### ISSUE THREAD

**Issue by j3g3pro** [khalim19/gimp-plugin-export-layers#94]
#### What went wrong?

Traceback (most recent call last):
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/gui/gui_plugin.py", line 198, in func_wrapper
    func(self, *args, **kwargs)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/gui/gui_plugin.py", line 821, in _on_button_export_clicked
    self._layer_exporter.export()
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/exportlayers.py", line 232, in export
    self._export_layers()
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/exportlayers.py", line 443, in _export_layers
    self._process_and_export_item(layer_elem)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/exportlayers.py", line 453, in _process_and_export_item
    layer_copy = self._process_layer(layer_elem, self._image_copy, layer)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/exportlayers.py", line 522, in _process_layer
    additional_args_position=0)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/pygimplib/pgoperations.py", line 259, in execute
    operation, operation_args, operation_kwargs, group)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/pygimplib/pgoperations.py", line 227, in _execute_operation_with_foreach_operations
    operation, operation_args, operation_kwargs)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/pygimplib/pgoperations.py", line 207, in _execute_operation
    return operation(*args, **kwargs)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/exportlayers.py", line 776, in _execute_operation
    return operation(*operation_args, **operation_kwargs)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/exportlayers.py", line 767, in _operation
    args, kwargs, image, layer, layer_exporter)
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/placeholders.py", line 96, in get_replaced_args_and_kwargs
    get_replaced_arg(arg, image, layer, layer_exporter) for arg in func_args]
  File "C:\Users\xD\AppData\Roaming\GIMP\2.10\plug-ins/export_layers/placeholders.py", line 81, in get_replaced_arg
    if arg in _PLACEHOLDERS.keys():
TypeError: can't compare gimpcolor.RGB to unicode

#### If you can, tell us the steps to reproduce the problem.
File
Export Layers

ExportLayersForm: Settings

ExportLayersForm: Show More Settings

ExportLayersForm: (X) Include Layers

ExportLayersForm: + Add Procedure

ExportLayersForm: Add script-fu-addborder

ExportLayersForm: Value X AddBorder = 9, Value Y AddBorder = 9.

ExportLayersForm:
There was a problem with updating the image preview.
If you believe this is an error in the plug-in, you can help fix it by sending a report with the text in the details to one of the sites below.

#### Configuration

Version of Export Layers: 3.3.1

Version of GIMP: 2.10.22

Operating system: 10.0.19042 Build 19042

**Comment by desmarty** [comment]
(Sorry to the developer) As this plugin is out dated or may be it is inactive on current issues, I made scripts for the same purpose. Please find it in [Gimp Scripts - Export layers](https://github.com/desmarty/gimp_script). (This is an essential part of gimp. So I had to develop it by myself. It is a script, so it may not be broken in future releases of gimp. I am working on other essential modules for gimp too. Hope it is helpful to someone. Thank you and again sorry to this developer as i am approximately promoting my repository here)

**Comment by khalim19** [comment]
Thanks for reporting this bug, I fixed it and will be included in the next release (hopefully soon!).

@desmarty  It's OK, I can totally understand that, given that I had been unresponsive for the past 3 years or so due to other commitments.

**Comment by desmarty** [comment]
@khalim19 wow.. woke up.. late.. :smile: The plugin users will be happy now.

**Comment by khalim19** [comment]
Fixed in 3.3.2.
